### PR TITLE
sqlparser: remove TruncateQuery and flag registrations

### PR DESCRIPTION
**Pull request by dt**
This removes the query tuncation helpers, and their cli flag
registrations, from the sqlparser package.

This is intended to be rebased in the cockroach fork, where we only care
about the sqlparser package and that it is usable as a library without
registering cli flags when linked in to another binary.

Note: This breaks downstream packages in vitess so it is *not* intended
to be sent upstream.

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]
LGTM. This patch is small enough I really think it's worth bringing up to the vitess people at least as a point of discussion. They might well say it's wrong to not be able to log in this package, but they might also say it's definitely wrong to log in this package.

**Comment by madelynnblue** [comment]
What downstream stuff is broken by this by the way? Do they have tests that depend on log output?

**Comment by dt** [comment]
the downstream stuff is broken by the first commit -- it deletes the truncation methods that have callers in other packages.

**Comment by madelynnblue** [comment]
Ah I didn't see that commit for some reason. My comment was only about the second commit.

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
